### ISSUE TITLE
Polyfill increases size...?!

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/webpack-vue-config#90]
Hey @skjnldsv,

i just realised, that the update to 4.0.1 increases the bundle on forms of around `30 KiB`. So we now have `2.5 MiB`, which was on vue-config 4 and below (before webpack 5) `2.47 MiB`.
Similar thing i see on password_policy, where it is now `380 KiB` instead of the `~330 KiB`, that it was... (still including the large translations).

I don't think the 30 KiB are a problem, i just thought it seems to me like the polyfill-plugin now adds some code, that we never had or needed... 🤔 But i honestly have no idea what that thing really does.... 🙈 

This more for your information, maybe you have an idea what it does or when it is necessary...
Greets :)
Jonas

**Comment by skjnldsv** [comment]
Hey!
So, it's an unfortunate change from webpack.
They removed all the automatic-already-included polyfills in webpack 5.

So we have to add them manually after.
They're aliased, so they're still only used on-demand. Nonetheless, yeah, there are some areas we could improve, but unfortunately, we have [to rely on this since webpack5](https://github.com/nextcloud/webpack-vue-config/pull/88#issue-602580374)

**Comment by jotoeri** [comment]
🤷‍♂️
